# -*- coding: utf-8 -*-
"""
================================================================
اسکریپت ۱۳ — افزودن دستی ۲ ایندکس DESC به Migration اولیه
================================================================
این اسکریپت فایل initial_schema migration را modify می‌کند تا
دو ایندکس expression-based DESC در AuditLog اضافه شوند که Alembic
در autogenerate skip کرده بود.

ایندکس‌های هدف (سند ۵.۱۲):
  1. idx_audit_user_created   on AuditLog(user_id, created_at DESC)
  2. idx_audit_action_created on AuditLog(action, created_at DESC)

دلیل skip شدن:
  Alembic در SQLite نمی‌تواند expression-based indexes را reflect کند:
    UserWarning: autogenerate skipping metadata-specified expression-based
    index 'idx_audit_user_created'; dialect 'sqlite' under SQLAlchemy 2.0.30
    can't reflect these indexes so they can't be compared

این اسکریپت چه می‌کند:
  1. آخرین فایل *_initial_schema.py در migrations/versions/ را پیدا می‌کند
  2. backup با پسوند .bak می‌سازد
  3. خطوط CREATE INDEX را قبل از پایان upgrade() اضافه می‌کند
  4. خطوط DROP INDEX را در ابتدای downgrade() اضافه می‌کند
  5. idempotent — اجرای دوم اثری ندارد (تشخیص بر اساس وجود نام ایندکس‌ها)

نحوه اجرا (در CMD 3):
    cd D:\\Projects\\trading-system
    python scripts\\13_add_desc_indexes_to_migration.py
================================================================
"""

import sys
from pathlib import Path

try:
    from colorama import Fore, Style
    from colorama import init as _colorama_init

    _colorama_init(autoreset=True)
    GREEN, RED, YELLOW, CYAN, BOLD, RESET = (
        Fore.GREEN,
        Fore.RED,
        Fore.YELLOW,
        Fore.CYAN,
        Style.BRIGHT,
        Style.RESET_ALL,
    )
except ImportError:
    GREEN = RED = YELLOW = CYAN = BOLD = RESET = ""


# ============================================================
# مسیرها
# ============================================================
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
BACKEND_DIR = PROJECT_ROOT / "backend"
VERSIONS_DIR = BACKEND_DIR / "migrations" / "versions"


# ============================================================
# Marker ها و قطعات کد برای جایگزینی
# ============================================================

# پایان upgrade — این فقط یک‌بار با replace(..., 1) جایگزین می‌شود
UPGRADE_END_MARKER = "    # ### end Alembic commands ###"

UPGRADE_REPLACEMENT = """    # ============================================================
    # Manual: Expression-based DESC indexes for AuditLog (Doc 5.12)
    # Alembic autogenerate skips these because SQLite cannot reflect
    # expression-based indexes (UserWarning during autogenerate).
    # Added via raw SQL using op.execute().
    # ============================================================
    op.execute(
        'CREATE INDEX idx_audit_user_created '
        'ON "AuditLog" (user_id, created_at DESC)'
    )
    op.execute(
        'CREATE INDEX idx_audit_action_created '
        'ON "AuditLog" (action, created_at DESC)'
    )

    # ### end Alembic commands ###"""


# ابتدای downgrade — این marker فقط یک‌بار در کل فایل وجود دارد
# (چون شامل خط `def downgrade` است)
DOWNGRADE_START_MARKER = (
    "def downgrade() -> None:\n"
    '    """Downgrade schema."""\n'
    "    # ### commands auto generated by Alembic - please adjust! ###"
)

DOWNGRADE_REPLACEMENT = (
    "def downgrade() -> None:\n"
    '    """Downgrade schema."""\n'
    "    # ### commands auto generated by Alembic - please adjust! ###\n"
    "\n"
    "    # ============================================================\n"
    "    # Manual: Drop expression-based DESC indexes (Doc 5.12)\n"
    "    # ============================================================\n"
    '    op.execute("DROP INDEX IF EXISTS idx_audit_action_created")\n'
    '    op.execute("DROP INDEX IF EXISTS idx_audit_user_created")\n'
)


# ============================================================
# توابع کمکی
# ============================================================


def info(msg: str) -> None:
    print(f"{CYAN}ℹ {msg}{RESET}")


def success(msg: str) -> None:
    print(f"{GREEN}✅ {msg}{RESET}")


def warn(msg: str) -> None:
    print(f"{YELLOW}⚠ {msg}{RESET}")


def err(msg: str) -> None:
    print(f"{RED}❌ {msg}{RESET}")


def header(msg: str) -> None:
    line = "=" * 60
    print(f"\n{BOLD}{CYAN}{line}{RESET}")
    print(f"{BOLD}{CYAN}{msg}{RESET}")
    print(f"{BOLD}{CYAN}{line}{RESET}\n")


def find_initial_migration() -> Path | None:
    """پیدا کردن جدیدترین فایل initial_schema در versions/."""
    if not VERSIONS_DIR.exists():
        return None
    candidates = list(VERSIONS_DIR.glob("*_initial_schema.py"))
    if not candidates:
        return None
    # اگر چند فایل وجود دارد، آخرین را از نظر mtime برمی‌گردانیم
    return max(candidates, key=lambda p: p.stat().st_mtime)


# ============================================================
# main
# ============================================================
def main() -> int:
    header("اسکریپت ۱۳ — افزودن ۲ ایندکس DESC به Migration اولیه")

    info(f"پوشه versions: {VERSIONS_DIR}")

    # پیدا کردن فایل migration
    migration_file = find_initial_migration()
    if migration_file is None:
        err("فایل *_initial_schema.py در migrations/versions/ یافت نشد.")
        err("ابتدا این دستور را اجرا کنید:")
        err('  alembic revision --autogenerate -m "initial_schema"')
        return 1

    info(f"فایل پیداشده: {migration_file.relative_to(PROJECT_ROOT)}")
    print()

    # خواندن محتوا
    try:
        content = migration_file.read_text(encoding="utf-8")
    except Exception as e:
        err(f"خطا در خواندن فایل: {e}")
        return 1

    # ===== چک idempotent =====
    has_user_idx = "idx_audit_user_created" in content
    has_action_idx = "idx_audit_action_created" in content

    if has_user_idx and has_action_idx:
        success("هر دو ایندکس از قبل در فایل وجود دارند — تغییری لازم نیست.")
        info("اسکریپت idempotent است: اجرای مجدد بدون اثر.")
        print()
        info("می‌توانید مستقیماً به گام بعد بروید: 'alembic upgrade head'")
        return 0

    # ===== bckup =====
    backup_path = migration_file.with_suffix(".py.bak")
    backup_path.write_text(content, encoding="utf-8")
    info(f"بک‌آپ ساخته شد: {backup_path.name}")
    print()

    # ===== modify upgrade() =====
    info("اضافه کردن خطوط CREATE INDEX به upgrade() ...")

    if UPGRADE_END_MARKER not in content:
        err(f"Marker پایان upgrade پیدا نشد: {UPGRADE_END_MARKER!r}")
        err("فرمت فایل migration غیرمنتظره است.")
        return 1

    # فقط اولین occurrence (که در upgrade() است) را جایگزین می‌کنیم
    new_content = content.replace(UPGRADE_END_MARKER, UPGRADE_REPLACEMENT, 1)
    if new_content == content:
        err("جایگزینی upgrade() ناموفق بود.")
        return 1

    success("upgrade() به‌روز شد")
    content = new_content

    # ===== modify downgrade() =====
    info("اضافه کردن خطوط DROP INDEX به ابتدای downgrade() ...")

    if DOWNGRADE_START_MARKER not in content:
        err("Marker ابتدای downgrade() پیدا نشد.")
        err("لطفاً فایل را به من نشان دهید (شاید فرمت autogen متفاوت است).")
        return 1

    new_content = content.replace(DOWNGRADE_START_MARKER, DOWNGRADE_REPLACEMENT, 1)
    if new_content == content:
        err("جایگزینی downgrade() ناموفق بود.")
        return 1

    success("downgrade() به‌روز شد")
    content = new_content

    # ===== نوشتن فایل =====
    migration_file.write_text(content, encoding="utf-8")
    success(f"فایل migration به‌روز شد: {migration_file.name}")
    print()

    # ===== خلاصه و گام بعدی =====
    header("خلاصه")
    print(f"  {GREEN}✓{RESET} ایندکس idx_audit_user_created    افزوده شد به upgrade()")
    print(f"  {GREEN}✓{RESET} ایندکس idx_audit_action_created  افزوده شد به upgrade()")
    print(f"  {GREEN}✓{RESET} هر دو DROP INDEX افزوده شدند به downgrade()")
    print(f"  {GREEN}✓{RESET} بک‌آپ نسخه قبلی: {backup_path.name}")
    print()

    header("گام بعدی — اعمال migration (ساخت فیزیکی جدول‌ها در DB)")

    info("⚠ uvicorn را با Ctrl+C متوقف کنید.\n")
    print(f"  {BOLD}cd D:\\Projects\\trading-system\\backend{RESET}")
    print(f"  {BOLD}venv\\Scripts\\activate{RESET}")
    print()

    print(
        f"{BOLD}{GREEN}# دستور ۱ — اعمال migration (ساخت ۱۵ جدول + ایندکس‌ها در trading.db):{RESET}"
    )
    print(f"  {BOLD}alembic upgrade head{RESET}")
    print()
    info("خروجی مورد انتظار:")
    info("  INFO [alembic.runtime.migration] Running upgrade  -> XXXX, initial_schema")
    print()

    print(f"{BOLD}{GREEN}# دستور ۲ — تأیید revision فعلی:{RESET}")
    print(f"  {BOLD}alembic current{RESET}")
    info("  باید revision ID شما را نمایش دهد (مثلاً 05acc664bbb6 (head))")
    print()

    print(f"{BOLD}{GREEN}# دستور ۳ — تأیید وجود ۱۵ جدول + ایندکس‌ها در DB:{RESET}")
    print(
        f"  {BOLD}python -c \"import sqlite3; c=sqlite3.connect('trading.db'); tables=[r[0] for r in c.execute(\\\"SELECT name FROM sqlite_master WHERE type='table' ORDER BY name\\\")]; print('Tables:', len(tables)); [print(' ', t) for t in tables]\"{RESET}"
    )
    info("  باید ۱۷ جدول نمایش داده شود: ۱۵ جدول پروژه + alembic_version + sqlite_sequence")
    print()

    print(f"{BOLD}{GREEN}# دستور ۴ — تأیید ایندکس‌های DESC:{RESET}")
    print(
        f"  {BOLD}python -c \"import sqlite3; c=sqlite3.connect('trading.db'); idx=[r for r in c.execute(\\\"SELECT name, sql FROM sqlite_master WHERE type='index' AND name LIKE 'idx_%' ORDER BY name\\\")]; [print(n, '->', s) for n, s in idx]\"{RESET}"
    )
    info("  باید ۴ ایندکس custom دیده شود (شامل DESC در دو مورد audit)")
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
