# -*- coding: utf-8 -*-
"""
54d_finalize_hooks.py — نهایی‌سازی pre-commit hooks بعد از کشف bug ها

تغییرات نسبت به نسخه قبلی:
  ۱. حذف mixed-line-ending hook (Git خودش با .gitattributes handle می‌کند)
  ۲. تبدیل cmd wrappers به Python wrappers (cross-platform)
  ۳. UTF-8 stdout fix در همه custom scripts (M9)
  ۴. ساخت .gitattributes برای کنترل CRLF/LF
  ۵. حذف موقت pytest-unit و vitest از pre-commit
     (اینها در نسخه بعدی به‌صورت pre-push hook اضافه می‌شوند)
"""

from __future__ import annotations

import io
import sys
from pathlib import Path

# UTF-8 stdout
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except AttributeError:
        pass

ROOT = Path(__file__).resolve().parent.parent


# ============================================================
# 1) .gitattributes - کنترل CRLF/LF
# ============================================================

GITATTRIBUTES = """# .gitattributes - line ending control
# Generated by 54d_finalize_hooks.py

# Default: LF in repository, native (CRLF) in working copy on Windows
*           text=auto

# Force LF (always Unix)
*.py        text eol=lf
*.md        text eol=lf
*.yaml      text eol=lf
*.yml       text eol=lf
*.json      text eol=lf
*.toml      text eol=lf
*.ini       text eol=lf
*.cfg       text eol=lf
*.jsx       text eol=lf
*.js        text eol=lf
*.ts        text eol=lf
*.tsx       text eol=lf
*.css       text eol=lf
*.html      text eol=lf
*.txt       text eol=lf
*.sh        text eol=lf
*.env*      text eol=lf

# Force CRLF (Windows-specific)
*.cmd       text eol=crlf
*.bat       text eol=crlf
*.ps1       text eol=crlf

# Binary files
*.png       binary
*.jpg       binary
*.gif       binary
*.ico       binary
*.pdf       binary
*.zip       binary
*.xlsx      binary
*.xlsm      binary
*.xls       binary
*.db        binary
*.sqlite*   binary
"""


# ============================================================
# 2) .pre-commit-config.yaml - نسخه نهایی
# ============================================================

PRECOMMIT_CONFIG_FINAL = """# Pre-commit configuration - Trading System (Final v2)
# T2.06 (chat 7) - bugs fixed
#
# Setup:
#   pip install pre-commit==3.7.1 black==24.4.2 isort==5.13.2
#   pre-commit install
#
# Run manually:
#   pre-commit run --all-files
#
# Emergency bypass:
#   git commit --no-verify -m "[skip-hooks: REASON] ..."

default_language_version:
  python: python3.11

# فقط روی فایل‌های staged اجرا کن (نه کل پروژه)
default_stages: [pre-commit]

repos:
  # ========== Built-in hooks (selective) ==========
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/.*\\.md$
      - id: end-of-file-fixer
        exclude: ^(.*\\.svg|.*\\.cmd|.*\\.bat)$
      - id: check-yaml
      - id: check-json
        exclude: ^frontend/package-lock\\.json$
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  # ========== Python: black (auto-fix) ==========
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        files: ^(backend/app/|backend/tests/|scripts/).*\\.py$
        args: ['--line-length=100']

  # ========== Python: isort (auto-fix) ==========
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^(backend/app/|backend/tests/|scripts/).*\\.py$
        args: ['--profile=black', '--line-length=100']

  # ========== Local custom hooks ==========
  - repo: local
    hooks:
      - id: check-anti-patterns
        name: Anti-Patterns A1-A10 check
        entry: python scripts/check_anti_patterns.py
        language: system
        types: [python]
        pass_filenames: false
"""


# ============================================================
# 3) check_anti_patterns.py - بازنویسی کامل با ASCII فقط
# ============================================================

CHECK_ANTI_PATTERNS_FINAL = '''# -*- coding: utf-8 -*-
"""
check_anti_patterns.py - custom pre-commit hook for A1-A10

Hybrid mode:
  - critical (A1, A4, A8, A10): fail commit
  - minor (A6 print): warning only

Usage:
  python scripts/check_anti_patterns.py            # check all files
  python scripts/check_anti_patterns.py --staged   # check git staged files

Notes:
  - ASCII-only output for Windows cp1252 compatibility
  - No emoji, no special Unicode in print()
"""

from __future__ import annotations

import io
import re
import subprocess
import sys
from pathlib import Path

# UTF-8 stdout for Windows
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except AttributeError:
        try:
            sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
            sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8")
        except Exception:
            pass

ROOT = Path(__file__).resolve().parent.parent

# ============================================================
# Rules
# ============================================================

CRITICAL = {
    "A1": {
        "name": "hex color hardcoded in JSX",
        "pattern": r"#[0-9a-fA-F]{3,6}\\b",
        "files": [".jsx"],
        "exclude_paths": ["frontend/src/themes/", "frontend/src/index.css"],
        "exclude_context": ["// theme-tokens-allowed"],
    },
    "A4": {
        "name": "hardcoded secret/password/api_key/token",
        "pattern": r\'\'\'(SECRET_KEY|PASSWORD|API_KEY|TOKEN)\\s*=\\s*["\\\'][^"\\\']{8,}["\\\']\'\'\',
        "files": [".py"],
        "exclude_paths": ["tests/", "scripts/"],
        "exclude_context": ["# noqa: secret-allowed", "settings.", "os.environ"],
    },
    "A8": {
        "name": "localStorage in JSX (use Zustand store instead)",
        "pattern": r"localStorage\\.(get|set)Item",
        "files": [".jsx"],
        "exclude_paths": ["frontend/src/stores/", "frontend/src/utils/storage"],
        "exclude_context": [],
    },
    "A10": {
        "name": "sync I/O (open/time.sleep/requests) in async context",
        "pattern": r"^\\s+(with open\\(|time\\.sleep|requests\\.)",
        "files": [".py"],
        "exclude_paths": ["scripts/", "tests/", "migrations/"],
        "exclude_context": ["# noqa: sync-allowed"],
    },
}

MINOR = {
    "A6": {
        "name": "print() instead of logger in backend",
        "pattern": r"^\\s*print\\(",
        "files": [".py"],
        "exclude_paths": ["scripts/", "tests/", "migrations/", "backend/main.py"],
        "exclude_context": ["# noqa: print-allowed"],
    },
}


def normalize_path(p: Path) -> str:
    """Return relative path with forward slashes (cross-platform)."""
    return str(p.relative_to(ROOT)).replace("\\\\", "/")


def get_staged_files() -> list[Path]:
    """Get git staged files."""
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            capture_output=True, text=True, check=True, encoding="utf-8",
        )
        return [ROOT / f for f in result.stdout.splitlines() if f.strip()]
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []


def get_all_project_files() -> list[Path]:
    """Get all Python and JSX files in the project."""
    files = []
    for pattern in ["backend/**/*.py", "scripts/**/*.py", "frontend/src/**/*.jsx"]:
        files.extend(ROOT.glob(pattern))
    return [f for f in files if "venv" not in str(f) and "node_modules" not in str(f)
            and "__pycache__" not in str(f)]


def check_file(path: Path, rule_id: str, rule: dict) -> list[str]:
    """Check one file against one rule. Return list of violations."""
    if not path.exists() or path.is_dir():
        return []

    if path.suffix not in rule["files"]:
        return []

    rel = normalize_path(path)
    for excl in rule["exclude_paths"]:
        if rel.startswith(excl):
            return []

    violations = []
    pattern = re.compile(rule["pattern"], re.MULTILINE)
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []

    lines = text.splitlines()
    for m in pattern.finditer(text):
        line_num = text[:m.start()].count("\\n") + 1
        line = lines[line_num - 1] if line_num <= len(lines) else ""

        # Skip if excluded context found
        if any(ctx in line for ctx in rule["exclude_context"]):
            continue

        # ASCII-safe output
        snippet = line.strip()[:100]
        violations.append(f"  [{rule_id}] {rel}:{line_num} -- {snippet}")

    return violations


def main() -> int:
    # Determine file list
    if "--staged" in sys.argv:
        files = get_staged_files()
        if not files:
            print("[INFO] No staged files. Use without --staged to check all.")
            return 0
    else:
        files = get_all_project_files()

    critical_violations = []
    minor_violations = []

    for rule_id, rule in CRITICAL.items():
        for f in files:
            for v in check_file(f, rule_id, rule):
                critical_violations.append((rule_id, rule["name"], v))

    for rule_id, rule in MINOR.items():
        for f in files:
            for v in check_file(f, rule_id, rule):
                minor_violations.append((rule_id, rule["name"], v))

    # Report (ASCII-only)
    print("=" * 64)
    print(f"  Anti-Patterns check ({len(files)} files scanned)")
    print("=" * 64)

    if critical_violations:
        print()
        print("=" * 64)
        print("  [FAIL] CRITICAL Anti-Pattern Violations -- commit aborted")
        print("=" * 64)
        for rule_id, name, v in critical_violations:
            print(f"\\n  [{rule_id}] {name}")
            print(v)
        print()

    if minor_violations:
        print()
        print("=" * 64)
        print("  [WARN] MINOR Anti-Pattern Warnings -- commit allowed")
        print("=" * 64)
        for rule_id, name, v in minor_violations:
            print(f"\\n  [{rule_id}] {name}")
            print(v)
        print()

    if critical_violations:
        print()
        print("[INFO] For emergency bypass:")
        print(\'   git commit --no-verify -m "[skip-hooks: REASON] ..."\')
        return 1

    if not critical_violations and not minor_violations:
        print()
        print("  [OK] No anti-patterns found.")
    else:
        print()
        print("  [OK] No critical violations. Minor warnings only.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


# ============================================================
# 4) حذف فایل‌های قدیمی .cmd wrapper (نیاز نداریم)
# ============================================================

OLD_FILES_TO_REMOVE = [
    "scripts/run_pytest_unit.cmd",
    "scripts/run_vitest.cmd",
]


# ============================================================
# Main
# ============================================================


def write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    print("=" * 64)
    print("  54d_finalize_hooks -- final fix for T2.06 hooks")
    print("=" * 64)
    print()

    changes = 0

    # 1) .gitattributes
    if write_if_changed(ROOT / ".gitattributes", GITATTRIBUTES):
        print("  [WRITE] .gitattributes")
        changes += 1
    else:
        print("  [SKIP]  .gitattributes (unchanged)")

    # 2) .pre-commit-config.yaml (rewrite)
    if write_if_changed(ROOT / ".pre-commit-config.yaml", PRECOMMIT_CONFIG_FINAL):
        print("  [WRITE] .pre-commit-config.yaml (rewritten)")
        changes += 1
    else:
        print("  [SKIP]  .pre-commit-config.yaml (unchanged)")

    # 3) check_anti_patterns.py (rewrite)
    if write_if_changed(ROOT / "scripts" / "check_anti_patterns.py", CHECK_ANTI_PATTERNS_FINAL):
        print("  [WRITE] scripts/check_anti_patterns.py (rewritten ASCII-only)")
        changes += 1
    else:
        print("  [SKIP]  scripts/check_anti_patterns.py (unchanged)")

    # 4) Remove old .cmd wrappers
    for rel in OLD_FILES_TO_REMOVE:
        p = ROOT / rel
        if p.exists():
            p.unlink()
            print(f"  [DELETE] {rel}")
            changes += 1
        else:
            print(f"  [SKIP]   {rel} (already absent)")

    print()
    print("=" * 64)
    if changes == 0:
        print("  [OK] idempotent -- no changes")
    else:
        print(f"  [OK] {changes} changes applied")
    print("=" * 64)
    print()
    print("Next steps:")
    print("  1. git add -A")
    print(
        '  2. git commit --no-verify -m "fix(tier2): T2.06 hooks final -- ASCII + Python wrappers"'
    )
    print("  3. Then re-run pre-commit:")
    print("     cd backend && venv\\\\Scripts\\\\activate && cd ..")
    print("     pre-commit run --all-files")
    print()
    print("  4. Many files will be reformatted by black/isort -- this is OK.")
    print("     git add -A && git commit -m 'style: apply black/isort to all files'")
    return 0


if __name__ == "__main__":
    sys.exit(main())
